<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RecetteSeeder extends Seeder
{
    public function run()
    {
        DB::table('recettes')->insert([
            ['id_recette' => 1, 'name' => 'Salade de tomates', 'desc' => 'Une délicieuse salade fraîche.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/1/600/400', 'id_origine' => 7,'public' => false, 'season' => 3, 'references' => (string)floor(time() * (1 / 2))],
            ['id_recette' => 2, 'name' => 'Poulet au beurre', 'desc' => 'Recette traditionnelle indienne.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/2/600/400', 'id_origine' => 22,'public' => false,  'season' => 4, 'references' => (string)floor(time() * (2 / 2))],
            ['id_recette' => 3, 'name' => 'Pizza maison', 'desc' => 'Une pizza garnie de légumes et viande.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/3/600/400', 'id_origine' => 40,'public' => true,  'season' => 2, 'references' => (string)floor(time() * (3 / 2))],
            ['id_recette' => 4, 'name' => 'Tarte aux pommes', 'desc' => 'Tarte traditionnelle française.', 'id_user' => 3, 'image' => 'https://picsum.photos/seed/4/600/400', 'id_origine' => 15,'public' => true,  'season' => 1, 'references' => (string)floor(time() * (4 / 2))],
            ['id_recette' => 5, 'name' => 'Boeuf bourguignon', 'desc' => 'Plat mijoté classique.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/5/600/400', 'id_origine' => 19,'public' => true,  'season' => 4, 'references' => (string)floor(time() * (5 / 2))],
            ['id_recette' => 6, 'name' => 'Quiche lorraine', 'desc' => 'Tarte salée aux lardons.', 'id_user' => 4, 'image' => 'https://picsum.photos/seed/6/600/400', 'id_origine' => 7,'public' => false,  'season' => 3, 'references' => (string)floor(time() * (6 / 2))],
            ['id_recette' => 7, 'name' => 'Soupe à l\'oignon', 'desc' => 'Soupe traditionnelle française.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/7/600/400', 'id_origine' => 8,'public' => false,  'season' => 1, 'references' => (string)floor(time() * (7 / 2))],
            ['id_recette' => 8, 'name' => 'Ratatouille', 'desc' => 'Plat provençal aux légumes.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/8/600/400', 'id_origine' => 12,'public' => false,  'season' => 3, 'references' => (string)floor(time() * (8 / 2))],
            ['id_recette' => 9, 'name' => 'Crêpes', 'desc' => 'Pâte fine sucrée ou salée.', 'id_user' => 3, 'image' => 'https://picsum.photos/seed/9/600/400', 'id_origine' => 5,'public' => true, 'season' => 2, 'references' => (string)floor(time() * (9 / 2))],
            ['id_recette' => 10, 'name' => 'Gratin dauphinois', 'desc' => 'Pommes de terre à la crème.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/10/600/400', 'id_origine' => 21,'public' => false,  'season' => 4, 'references' => (string)floor(time() * (10 / 2))],
            ['id_recette' => 11, 'name' => 'Tajine de poulet', 'desc' => 'Plat marocain épicé.', 'id_user' => 4, 'image' => 'https://picsum.photos/seed/11/600/400', 'id_origine' => 11,'public' => true,  'season' => 2, 'references' => (string)floor(time() * (11 / 2))],
            ['id_recette' => 12, 'name' => 'Sushi', 'desc' => 'Spécialité japonaise de riz.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/12/600/400', 'id_origine' => 32,'public' => false,  'season' => 1, 'references' => (string)floor(time() * (12 / 2))],
            ['id_recette' => 13, 'name' => 'Chili con carne', 'desc' => 'Plat épicé tex-mex.', 'id_user' => 3, 'image' => 'https://picsum.photos/seed/13/600/400', 'id_origine' => 28,'public' => true,  'season' => 3, 'references' => (string)floor(time() * (13 / 2))],
            ['id_recette' => 14, 'name' => 'Paella', 'desc' => 'Plat espagnol de riz.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/14/600/400', 'id_origine' => 17,'public' => false, 'season' => 4, 'references' => (string)floor(time() * (14 / 2))],
            ['id_recette' => 15, 'name' => 'Gaufres', 'desc' => 'Pâtisserie croustillante.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/15/600/400', 'id_origine' => 6,'public' => true,  'season' => 1, 'references' => (string)floor(time() * (15 / 2))],
            ['id_recette' => 16, 'name' => 'Lasagnes', 'desc' => 'Plat italien en couches.', 'id_user' => 3, 'image' => 'https://picsum.photos/seed/16/600/400', 'id_origine' => 29,'public' => false,  'season' => 3, 'references' => (string)floor(time() * (16 / 2))],
            ['id_recette' => 17, 'name' => 'Hamburger maison', 'desc' => 'Burger avec viande et légumes.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/17/600/400', 'id_origine' => 20, 'public' => true, 'season' => 2, 'references' => (string)floor(time() * (17 / 2))],
            ['id_recette' => 18, 'name' => 'Couscous', 'desc' => 'Plat nord-africain traditionnel.', 'id_user' => 4, 'image' => 'https://picsum.photos/seed/18/600/400', 'id_origine' => 13, 'public' => false, 'season' => 4, 'references' => (string)floor(time() * (18 / 2))],
            ['id_recette' => 19, 'name' => 'Fondue savoyarde', 'desc' => 'Fromage fondu traditionnel.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/19/600/400', 'id_origine' => 16,'public' => true,  'season' => 1, 'references' => (string)floor(time() * (19 / 2))],
            ['id_recette' => 20, 'name' => 'Crème brûlée', 'desc' => 'Dessert à la vanille.', 'id_user' => 3, 'image' => 'https://picsum.photos/seed/20/600/400', 'id_origine' => 4, 'public' => false, 'season' => 3, 'references' => (string)floor(time() * (20 / 2))],
            ['id_recette' => 21, 'name' => 'Poulet rôti', 'desc' => 'Poulet cuit au four.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/21/600/400', 'id_origine' => 9, 'public' => true, 'season' => 2, 'references' => (string)floor(time() * (21 / 2))],
            ['id_recette' => 22, 'name' => 'Mousse au chocolat', 'desc' => 'Dessert mousseux.', 'id_user' => 4, 'image' => 'https://picsum.photos/seed/22/600/400', 'id_origine' => 3,'public' => false,  'season' => 4, 'references' => (string)floor(time() * (22 / 2))],
            ['id_recette' => 23, 'name' => 'Riz cantonais', 'desc' => 'Riz sauté chinois.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/23/600/400', 'id_origine' => 31, 'public' => true, 'season' => 1, 'references' => (string)floor(time() * (23 / 2))],
            ['id_recette' => 24, 'name' => 'Bouillabaisse', 'desc' => 'Soupe de poissons provençale.', 'id_user' => 3, 'image' => 'https://picsum.photos/seed/24/600/400', 'id_origine' => 18, 'public' => false, 'season' => 3, 'references' => (string)floor(time() * (24 / 2))],
            ['id_recette' => 25, 'name' => 'Salade César', 'desc' => 'Salade avec poulet et parmesan.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/25/600/400', 'id_origine' => 10,'public' => true,  'season' => 4, 'references' => (string)floor(time() * (25 / 2))],
            ['id_recette' => 26, 'name' => 'Crêpes Suzette', 'desc' => 'Crêpes flambées à l\'orange.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/26/600/400', 'id_origine' => 5, 'public' => false, 'season' => 1, 'references' => (string)floor(time() * (26 / 2))],
            ['id_recette' => 27, 'name' => 'Falafel', 'desc' => 'Boulettes de pois chiches.', 'id_user' => 4, 'image' => 'https://picsum.photos/seed/27/600/400', 'id_origine' => 14,'public' => true,  'season' => 3, 'references' => (string)floor(time() * (27 / 2))],
            ['id_recette' => 28, 'name' => 'Choucroute', 'desc' => 'Plat alsacien à base de chou.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/28/600/400', 'id_origine' => 8, 'public' => false, 'season' => 2, 'references' => (string)floor(time() * (28 / 2))],
            ['id_recette' => 29, 'name' => 'Tiramisu', 'desc' => 'Dessert italien au café.', 'id_user' => 3, 'image' => 'https://picsum.photos/seed/29/600/400', 'id_origine' => 30, 'public' => true, 'season' => 4, 'references' => (string)floor(time() * (29 / 2))],
            ['id_recette' => 30, 'name' => 'Salade niçoise', 'desc' => 'Salade méditerranéenne.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/30/600/400', 'id_origine' => 7,'public' => false,  'season' => 1, 'references' => (string)floor(time() * (30 / 2))],
            ['id_recette' => 31, 'name' => 'Curry de légumes', 'desc' => 'Plat végétarien épicé.', 'id_user' => 4, 'image' => 'https://picsum.photos/seed/31/600/400', 'id_origine' => 23,'public' => true,  'season' => 3, 'references' => (string)floor(time() * (31 / 2))],
            ['id_recette' => 32, 'name' => 'Boulette de viande', 'desc' => 'Viande hachée en boulettes.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/32/600/400', 'id_origine' => 19, 'public' => false, 'season' => 2, 'references' => (string)floor(time() * (32 / 2))],
            ['id_recette' => 33, 'name' => 'Salade de fruits', 'desc' => 'Mélange de fruits frais.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/33/600/400', 'id_origine' => 6, 'public' => true, 'season' => 4, 'references' => (string)floor(time() * (33 / 2))],
            ['id_recette' => 34, 'name' => 'Pancakes', 'desc' => 'Crêpes épaisses américaines.', 'id_user' => 3, 'image' => 'https://picsum.photos/seed/34/600/400', 'id_origine' => 5,'public' => false,  'season' => 1, 'references' => (string)floor(time() * (34 / 2))],
            ['id_recette' => 35, 'name' => 'Soupe miso', 'desc' => 'Soupe japonaise traditionnelle.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/35/600/400', 'id_origine' => 33,'public' => true,  'season' => 3, 'references' => (string)floor(time() * (35 / 2))],
            ['id_recette' => 36, 'name' => 'Gratin de courgettes', 'desc' => 'Légumes gratinés au four.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/36/600/400', 'id_origine' => 12,'public' => false,  'season' => 2, 'references' => (string)floor(time() * (36 / 2))],
            ['id_recette' => 37, 'name' => 'Boeuf carottes', 'desc' => 'Plat mijoté simple.', 'id_user' => 4, 'image' => 'https://picsum.photos/seed/37/600/400', 'id_origine' => 19,'public' => true,  'season' => 4, 'references' => (string)floor(time() * (37 / 2))],
            ['id_recette' => 38, 'name' => 'Gaspacho', 'desc' => 'Soupe froide espagnole.', 'id_user' => 3, 'image' => 'https://picsum.photos/seed/38/600/400', 'id_origine' => 17,'public' => false,  'season' => 1, 'references' => (string)floor(time() * (38 / 2))],
            ['id_recette' => 39, 'name' => 'Salade de quinoa', 'desc' => 'Salade saine et nutritive.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/39/600/400', 'id_origine' => 6,'public' => true,  'season' => 3, 'references' => (string)floor(time() * (39 / 2))],
            ['id_recette' => 40, 'name' => 'Tarte au citron', 'desc' => 'Dessert acidulé.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/40/600/400', 'id_origine' => 5, 'public' => false, 'season' => 4, 'references' => (string)floor(time() * (40 / 2))]
        ]);
    }
}
