<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RecetteSeeder extends Seeder
{
    public function run()
    {
        DB::table('recettes')->insert([
            ['id_recette' => 1, 'name' => 'Salade de tomates', 'desc' => 'Une délicieuse salade fraîche.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/1/600/400'],
            ['id_recette' => 2, 'name' => 'Poulet au beurre', 'desc' => 'Recette traditionnelle indienne.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/2/600/400'],
            ['id_recette' => 3, 'name' => 'Pizza maison', 'desc' => 'Une pizza garnie de légumes et viande.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/3/600/400'],
            ['id_recette' => 4, 'name' => 'Tarte salée', 'desc' => 'Une tarte rustique à base de pâte maison.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/4/600/400'],
            ['id_recette' => 5, 'name' => 'Crêpes aux fruits', 'desc' => 'Des crêpes sucrées garnies de fruits frais.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/5/600/400'],
            ['id_recette' => 6, 'name' => 'Curry de légumes', 'desc' => 'Un curry doux et parfumé aux épices indiennes.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/6/600/400'],
            ['id_recette' => 7, 'name' => 'Lasagnes végétariennes', 'desc' => 'Des lasagnes sans viande mais pleines de goûts.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/7/600/400'],
            ['id_recette' => 8, 'name' => 'Soupe de courgettes', 'desc' => 'Une soupe onctueuse et légère.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/8/600/400'],
            ['id_recette' => 9, 'name' => 'Burger maison', 'desc' => 'Un burger complet fait maison.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/9/600/400'],
            ['id_recette' => 10, 'name' => 'Gratin dauphinois', 'desc' => 'Pommes de terre crémeuses au four.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/10/600/400'],
            ['id_recette' => 11, 'name' => 'Omelette aux champignons', 'desc' => 'Simple et rapide, parfait pour le déjeuner.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/11/600/400'],
            ['id_recette' => 12, 'name' => 'Soupe de lentilles', 'desc' => 'Riche en protéines et très nourrissante.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/12/600/400'],
            ['id_recette' => 13, 'name' => 'Chili sin carne', 'desc' => 'Une alternative végé au chili classique.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/13/600/400'],
            ['id_recette' => 14, 'name' => 'Tarte à la rhubarbe', 'desc' => 'Acidulée et sucrée, un délice.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/14/600/400'],
            ['id_recette' => 15, 'name' => 'Gaufres au miel', 'desc' => 'Moelleuses avec une touche de miel.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/15/600/400'],
            ['id_recette' => 16, 'name' => 'Paella végétarienne', 'desc' => 'Un plat espagnol riche en saveurs.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/16/600/400'],
            ['id_recette' => 17, 'name' => 'Brochettes de tofu', 'desc' => 'Idéales pour un barbecue sain.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/17/600/400'],
            ['id_recette' => 18, 'name' => 'Spaghetti carbonara', 'desc' => 'Recette italienne crémeuse et savoureuse.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/18/600/400'],
            ['id_recette' => 19, 'name' => 'Clafoutis aux cerises', 'desc' => 'Un dessert classique français.', 'id_user' => 1, 'image' => 'https://picsum.photos/seed/19/600/400'],
            ['id_recette' => 20, 'name' => 'Boeuf bourguignon', 'desc' => 'Un plat mijoté traditionnel.', 'id_user' => 2, 'image' => 'https://picsum.photos/seed/20/600/400'],
            [
                'id_recette' => 21,
                'name' => 'Quiche aux épinards',
                'desc' => 'Quiche savoureuse aux épinards frais.',
                'id_user' => 2,
                'image' => 'https://picsum.photos/seed/quiche21/400/300',
            ],
            [
                'id_recette' => 22,
                'name' => 'Soupe de potiron',
                'desc' => 'Soupe onctueuse de potiron et crème.',
                'id_user' => 1,
                'image' => 'https://picsum.photos/seed/soupe22/400/300',
            ],
            [
                'id_recette' => 23,
                'name' => 'Burger végétarien',
                'desc' => 'Burger gourmand sans viande, aux légumes frais.',
                'id_user' => 1,
                'image' => 'https://picsum.photos/seed/burger23/400/300',
            ],
            [
                'id_recette' => 24,
                'name' => 'Riz sauté aux légumes',
                'desc' => 'Plat asiatique simple et rapide.',
                'id_user' => 2,
                'image' => 'https://picsum.photos/seed/riz24/400/300',
            ],
            [
                'id_recette' => 25,
                'name' => 'Tacos au poisson',
                'desc' => 'Tacos frais avec filet de poisson pané.',
                'id_user' => 1,
                'image' => 'https://picsum.photos/seed/tacos25/400/300',
            ],
            [
                'id_recette' => 26,
                'name' => 'Salade César',
                'desc' => 'Salade classique avec poulet et croûtons.',
                'id_user' => 1,
                'image' => 'https://picsum.photos/seed/salade26/400/300',
            ],
            [
                'id_recette' => 27,
                'name' => 'Curry de légumes',
                'desc' => 'Curry épicé aux légumes variés.',
                'id_user' => 2,
                'image' => 'https://picsum.photos/seed/curry27/400/300',
            ],
            [
                'id_recette' => 28,
                'name' => 'Gratin dauphinois',
                'desc' => 'Pommes de terre au four avec crème et fromage.',
                'id_user' => 1,
                'image' => 'https://picsum.photos/seed/gratin28/400/300',
            ],
            [
                'id_recette' => 29,
                'name' => 'Pâtes à la carbonara',
                'desc' => 'Pâtes crémeuses avec lardons et parmesan.',
                'id_user' => 2,
                'image' => 'https://picsum.photos/seed/pates29/400/300',
            ],
            [
                'id_recette' => 30,
                'name' => 'Brochettes de poulet',
                'desc' => 'Brochettes marinées et grillées.',
                'id_user' => 1,
                'image' => 'https://picsum.photos/seed/brochette30/400/300',
            ],
            [
                'id_recette' => 31,
                'name' => 'Salade de quinoa',
                'desc' => 'Quinoa avec légumes croquants et herbes fraîches.',
                'id_user' => 2,
                'image' => 'https://picsum.photos/seed/quinoa31/400/300',
            ],
            [
                'id_recette' => 32,
                'name' => 'Chili con carne',
                'desc' => 'Plat épicé à base de viande hachée et haricots.',
                'id_user' => 1,
                'image' => 'https://picsum.photos/seed/chili32/400/300',
            ],
            [
                'id_recette' => 33,
                'name' => 'Omelette aux fines herbes',
                'desc' => 'Omelette légère parfumée aux herbes fraîches.',
                'id_user' => 1,
                'image' => 'https://picsum.photos/seed/omelette33/400/300',
            ],
            [
                'id_recette' => 34,
                'name' => 'Filet de saumon grillé',
                'desc' => 'Saumon frais grillé avec citron.',
                'id_user' => 2,
                'image' => 'https://picsum.photos/seed/saumon34/400/300',
            ],
            [
                'id_recette' => 35,
                'name' => 'Tarte aux pommes',
                'desc' => 'Dessert classique avec pommes et pâte croustillante.',
                'id_user' => 1,
                'image' => 'https://picsum.photos/seed/tarte35/400/300',
            ],
            [
                'id_recette' => 36,
                'name' => 'Gaufres maison',
                'desc' => 'Gaufres croustillantes à servir avec sirop.',
                'id_user' => 2,
                'image' => 'https://picsum.photos/seed/gaufres36/400/300',
            ],
            [
                'id_recette' => 37,
                'name' => 'Salade grecque',
                'desc' => 'Tomates, concombres, feta et olives noires.',
                'id_user' => 1,
                'image' => 'https://picsum.photos/seed/grecque37/400/300',
            ],
            [
                'id_recette' => 38,
                'name' => 'Pancakes aux myrtilles',
                'desc' => 'Pancakes moelleux avec fruits frais.',
                'id_user' => 2,
                'image' => 'https://picsum.photos/seed/pancakes38/400/300',
            ],
            [
                'id_recette' => 39,
                'name' => 'Ratatouille',
                'desc' => 'Mélange provençal de légumes mijotés.',
                'id_user' => 1,
                'image' => 'https://picsum.photos/seed/ratatouille39/400/300',
            ],
            [
                'id_recette' => 40,
                'name' => 'Soupe minestrone',
                'desc' => 'Soupe italienne aux légumes variés.',
                'id_user' => 2,
                'image' => 'https://picsum.photos/seed/minestrone40/400/300',
            ],
            [
                'id_recette' => 41,
                'name' => 'Tajine de légumes',
                'desc' => 'Plat marocain mijoté aux épices.',
                'id_user' => 1,
                'image' => 'https://picsum.photos/seed/tajine41/400/300',
            ],
            [
                'id_recette' => 42,
                'name' => 'Mousse au chocolat',
                'desc' => 'Dessert léger et aérien au chocolat.',
                'id_user' => 2,
                'image' => 'https://picsum.photos/seed/mousse42/400/300',
            ],
            [
                'id_recette' => 43,
                'name' => 'Couscous royal',
                'desc' => 'Couscous avec viande et légumes variés.',
                'id_user' => 1,
                'image' => 'https://picsum.photos/seed/couscous43/400/300',
            ],
            [
                'id_recette' => 44,
                'name' => 'Salade de betteraves',
                'desc' => 'Betteraves fraîches avec vinaigrette légère.',
                'id_user' => 2,
                'image' => 'https://picsum.photos/seed/betteraves44/400/300',
            ],
            [
                'id_recette' => 45,
                'name' => 'Pain perdu',
                'desc' => 'Tranches de pain dorées au beurre et sucre.',
                'id_user' => 1,
                'image' => 'https://picsum.photos/seed/painperdu45/400/300',
            ],
            [
                'id_recette' => 46,
                'name' => 'Poulet rôti',
                'desc' => 'Poulet entier rôti aux herbes de Provence.',
                'id_user' => 2,
                'image' => 'https://picsum.photos/seed/poulet46/400/300',
            ],
            [
                'id_recette' => 47,
                'name' => 'Salade niçoise',
                'desc' => 'Salade avec thon, œufs, olives et légumes.',
                'id_user' => 1,
                'image' => 'https://picsum.photos/seed/nicoise47/400/300',
            ],
            [
                'id_recette' => 48,
                'name' => 'Lasagnes',
                'desc' => 'Lasagnes maison à la viande et béchamel.',
                'id_user' => 2,
                'image' => 'https://picsum.photos/seed/lasagnes48/400/300',
            ],
            [
                'id_recette' => 49,
                'name' => 'Crème brûlée',
                'desc' => 'Dessert à la crème caramélisée.',
                'id_user' => 1,
                'image' => 'https://picsum.photos/seed/creme49/400/300',
            ],
            [
                'id_recette' => 50,
                'name' => 'Filet mignon sauce moutarde',
                'desc' => 'Filet mignon tendre avec sauce onctueuse.',
                'id_user' => 2,
                'image' => 'https://picsum.photos/seed/filet50/400/300',
            ],
        ]);
    }
}
